services:
  db:
    image: postgres:15-alpine
    container_name: optisaas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: optisaas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: optisaas-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db:5432/optisaas?schema=public"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
      WATCHPACK_POLLING: "true"
      WEBPACK_WATCH_OPTIONS_POLL: "500"
      NG_CLI_ANALYTICS: "false"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: optisaas-frontend
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
      WATCHPACK_POLLING: "true"
      WEBPACK_WATCH_OPTIONS_POLL: "500"
      NG_CLI_ANALYTICS: "false"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: optisaas-prisma-studio
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db:5432/optisaas?schema=public"
    command: npx prisma studio --browser none
    depends_on:
      - db

volumes:
  pgdata:
